[project]
name = "hv25-t06-parmanu-shakti"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-google-genai>=2.1.2",
    "open-deep-research>=0.0.10",
    "streamlit>=1.44.1",
]
